[package]
name = "password_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "cargo"] }
colored = "2.1.0"
colorize = "0.1.0"
copypasta = "0.10.1"
crossterm = "0.27.0"
passwords = "3.1.16"
rand = "0.8.5"
